### ISSUE TITLE
Index Error

### ISSUE THREAD

**Issue by Han8931** [rivercold/BERT-unsupervised-OOD#1]
I got the following error when I tried to run

```
python ood_main.py --method MDF --data_type clinic --model_class bert
```

Error:
```
batch_all_features = self.get_hidden_features(**inputs, use_cls=use_cls)
all_hidden_feats = outputs[1]   # list (13) of bs x length x hidden
IndexError: tuple index out of range
```

Could you help me to solve this error?

I have installed all the requirements as you specified

**Comment by rivercold** [comment]
Hi Han,

Thank you for letting me know. I am wondering if you could download the IMLM+BCAD model in README and check if the following command works?

```
python ood_main.py \
  --method MDF \
  --data_type clinic \
  --model_class roberta \
  --load_path  ./models/roberta_clinic_ft_IMLM_BCAD
```

**Comment by Han8931** [comment]
> Hi Han,
> 
> Thank you for letting me know. I am wondering if you could download the IMLM+BCAD model in README and check if the following command works?
> 
> ```
> python ood_main.py \
>   --method MDF \
>   --data_type clinic \
>   --model_class roberta \
>   --load_path  ./models/roberta_clinic_ft_IMLM_BCAD
> ```

How to set up the path for the pre-trained models?

**Comment by Han8931** [comment]
> Hi Han,
> 
> Thank you for letting me know. I am wondering if you could download the IMLM+BCAD model in README and check if the following command works?
> 
> ```
> python ood_main.py \
>   --method MDF \
>   --data_type clinic \
>   --model_class roberta \
>   --load_path  ./models/roberta_clinic_ft_IMLM_BCAD
> ```

I got this error when I try to run the following command

CUDA_VISIBLE_DEVICES=6 python ood_main.py --method MDF --data_type sst --model_class roberta --load_path ./models/roberta_sst_ft_IMLM_BCAD

FileNotFoundError: [Errno 2] No such file or directory: './outputs/sst_roberta_roberta_sst_ft_IMLM_BCAD.pkl'

**Comment by Han8931** [comment]
> Hi Han,
> 
> Thank you for letting me know. I am wondering if you could download the IMLM+BCAD model in README and check if the following command works?
> 
> ```
> python ood_main.py \
>   --method MDF \
>   --data_type clinic \
>   --model_class roberta \
>   --load_path  ./models/roberta_clinic_ft_IMLM_BCAD
> ```

Thanks it seems working for pretrained models.
However, I want to test on different datasets.
Could you fix the issue?

**Comment by Han8931** [comment]
I still have this issue 

My library setup:

    Python 3.7.3
    PyTorch 1.2
    Transformers 2.7.0
    simpletransformers 0.22.1

and I tried to run the following command
```CUDA_VISIBLE_DEVICES=6 python ood_main.py --method MDF --data_type sst --model_class roberta```

Traceback (most recent call last):
  File "ood_main.py", line 521, in <module>
    main(args)
  File "ood_main.py", line 499, in main
    MDF_OOD_detect(args)   # our method 
  File "ood_main.py", line 328, in MDF_OOD_detect
    mean_list, precision_list = model.sample_X_estimator(train_df['text'].values.tolist(), use_cls)
  File "/data/han/BERT-unsupervised-OOD/our_model.py", line 54, in sample_X_estimator
    batch_all_features = self.get_hidden_features(**inputs, use_cls=use_cls)
  File "/data/han/BERT-unsupervised-OOD/our_model.py", line 186, in get_hidden_features
    all_hidden_feats = outputs[1]   # list (13) of bs x length x hidden
IndexError: tuple index out of range

**Comment by rivercold** [comment]
There was indeed an issue with the base model and I fixed it. I am wondering if this command works for you now.  
`CUDA_VISIBLE_DEVICES=6 python ood_main.py --method MDF --data_type sst --model_class roberta`

**Comment by Han8931** [comment]
> There was indeed an issue with the base model and I fixed it. I am wondering if this command works for you now.
> `CUDA_VISIBLE_DEVICES=6 python ood_main.py --method MDF --data_type sst --model_class roberta`

It is working well now thanks :)
