### ISSUE TITLE
Fine-tuning for different dataset

### ISSUE THREAD

**Issue by Han8931** [rivercold/BERT-unsupervised-OOD#3]
Hi, 
I wonder how can I train a full model for different datasets. 
I want to test your approach on different setups :)

**Comment by rivercold** [comment]
Hi Han,
For a new dataset, you need to add a few lines of codes here https://github.com/rivercold/BERT-unsupervised-OOD/blob/main/ood_main.py#L311 to support your customized `data_type`. 

Then you can use a base (Ro)BERT(a) model to run OOD detection, or further fine-tune the base model with IMLM + BCAD using `finetune_bert.py`. The commands are in the README file.

**Comment by Han8931** [comment]
You mean I have to run the command below 

```
python finetune_bert.py \
    --type finetune_imlm \ 
    --data_type clinic \ 
    --model_class bert
```
and run the command below with the saved model from the above one?
```
python finetune_bert.py \
    --type finetune_binary \ 
    --data_type clinic \ 
    --model_class bert
    --load_path xxx
```

**Comment by rivercold** [comment]
Yes, change `data_type` to your customized one though.
