### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './outputs/clinic_bert_bert-base-uncased.pkl'

### ISSUE THREAD

**Issue by minkyukim10** [rivercold/BERT-unsupervised-OOD#4]
Hi guys,

when I ran: 

!python ood_main.py \
  --method MDF \
  --data_type clinic \
  --model_class bert

I'm getting this error:

Work on different intents
train 15000 test 4500 ood 1000
---------- Use AVG embebeddings to represent sequence ----------
INFO:simpletransformers.classification.classification_model: Converting to features started. Cache is not used.
INFO:simpletransformers.classification.classification_model: Converting to features started. Cache is not used.
INFO:simpletransformers.classification.classification_model: Converting to features started. Cache is not used.
INFO:simpletransformers.classification.classification_model: Converting to features started. Cache is not used.
running ---: kernel: linear nuu: 1e-09
running ---: kernel: linear nuu: 1e-07
running ---: kernel: linear nuu: 1e-05
running ---: kernel: linear nuu: 0.001
running ---: kernel: linear nuu: 0.01
running ---: kernel: linear nuu: 0.1
running ---: kernel: linear nuu: 0.2
running ---: kernel: linear nuu: 0.5
 AUROC  DTACC  AUIN   AUOUT 
 76.72  71.11  93.41  38.19
best hyper linear-0.5
saving data for plotting
Traceback (most recent call last):
  File "ood_main.py", line 506, in <module>
    main(args)
  File "ood_main.py", line 484, in main
    MDF_OOD_detect(args)   # our method 
  File "ood_main.py", line 381, in MDF_OOD_detect
    with open("./outputs/{}_{}_{}.pkl".format(data_type, args.model_class, load_path.split("/")[-1]), "wb") as f:
FileNotFoundError: [Errno 2] No such file or directory: './outputs/clinic_bert_bert-base-uncased.pkl'

Any idea how I can resolve this issue?

Many thanks in advance,
Min

**Comment by rivercold** [comment]
Hi Min,

Before running the code, please create a directory `outputs` to save the results.

**Comment by minkyukim10** [comment]
Many thanks, it's working now.
