### ISSUE TITLE
data file structure: clinc150_test & clinc150_val

### ISSUE THREAD

**Issue by minkyukim10** [rivercold/BERT-unsupervised-OOD#5]
Hi OP,

Could you please tell me the purpose of the file (and also appearing in the JSON file): clinc150_val.

Also, just to double check - clinic150_test is 4500 lines of unseen in-domain data right? How is this different from clinc150_val?

Once again, many thanks in advance,
Min

**Comment by rivercold** [comment]
Hi Min,
 
Yes, for the test data on clinic150, only the "test" field was included. The 'val' (validation) field was not used. 

The 'valid' data was only used for early stopping in two fine-tuning experiments and I didn't use its intent labels.
