### ISSUE TITLE
Error when running roberta with our own finetuned data

### ISSUE THREAD

**Issue by nowackip** [rivercold/BERT-unsupervised-OOD#6]
Hello,
We are trying to run roberta model with our finetuned output data (we are using our own data set) with the following:

> !python ood_main.py \
>   --method MDF \
>   --data_type clinic \
>   --model_class roberta \
>   --load_path ./model/bert_clinic_ft_MLM_binary_intent_outputs_7500

and get the following error:

> ---------- Use AVG embebeddings to represent sequence ----------
> INFO:simpletransformers.classification.classification_model: Converting to features started. Cache is not used.
> Traceback (most recent call last):
>   File "ood_main.py", line 506, in <module>
>     main(args)
>   File "ood_main.py", line 484, in main
>     MDF_OOD_detect(args)   # our method 
>   File "ood_main.py", line 326, in MDF_OOD_detect
>     mean_list, precision_list = model.sample_X_estimator(train_df['text'].values.tolist(), use_cls)
>   File "/home/ec2-user/SageMaker/BERT-unsupervised-OOD/our_model.py", line 115, in sample_X_estimator
>     eval_examples, evaluate=True, multi_label=False, no_cache=True
>   File "/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/simpletransformers/classification/classification_model.py", line 757, in load_and_cache_examples
>     all_input_ids = torch.tensor([f.input_ids for f in features], dtype=torch.long)
> TypeError: an integer is required (got type NoneType)

Any idea what might be wrong?

Before, we had to modify the our_model.py fragment:
 
from:

`self.tokenizer = tokenizer_class.from_pretrained(model_name, do_lower_case=self.args["do_lower_case"], **kwargs)`

to:

`self.tokenizer = tokenizer_class.from_pretrained(model_name, 
vocab_file="./models/bert_clinic_ft_MLM_binary_intent_outputs_7500/checkpoint-2000/vocab.json", merges_file="./models/bert_clinic_ft_MLM_binary_intent_outputs_7500/checkpoint-2000/merges.txt",
do_lower_case=self.args["do_lower_case"], **kwargs)`

this was needed because the method was unable to find vocab and merges files. Those files where nowhere to be seen (except the vocab.txt file which seems to be wrong) in the given folder, so we got it from : 
https://huggingface.co/roberta-base/resolve/main/vocab.json
https://huggingface.co/roberta-base/resolve/main/merges.txt
hope it is still ok :)

Anyway, any help about this "TypeError: an integer is required (got type NoneType)" would be much appreciated! thanks!
Pawel

**Comment by rivercold** [comment]
Hi Pawel,

I am so sorry for the late reply. Which version of simpletransformer and transformer are you using? I am wondering if it is possible to share your fine-tuned model with me so I can do some testing on my side? You can email me the link to download it, if possible.

Keyang

**Comment by rivercold** [comment]
Hi Pawal,  I am going to close this issue. If you have any questions, feel free to reopen it or email me.
