### ISSUE TITLE
A question about  gaussian_score in the code

### ISSUE THREAD

**Issue by RachelTeamo** [rivercold/BERT-unsupervised-OOD#7]
Hi， I have read this wonderful paper. When I look at the code， I have a question.
[https://github.com/rivercold/BERT-unsupervised-OOD/blob/main/our_model.py#L181]()
In the our_model.py line 181,you define the gaussian score that: 
`gaussian_score = -0.5 * ((zero_f @ precision[i]) @ zero_f.t()).diag()`
But in your paper, I gauss this gaussian_score is the $M_{l}(x_{i})$, But I wonder why you don't use the inverse of a matrix precision[i] in the code. I also wonder why there is a -0.5 before this equation.
Thanks a lot.

**Comment by RechelTeamo** [comment]
I also wonder why there is a -0.5 before this equation.

**Comment by rivercold** [comment]
Hi,

The matrix inverse of the covariance matrix, is often called the precision matrix. You can check this link https://scikit-learn.org/stable/modules/generated/sklearn.covariance.EmpiricalCovariance.html#sklearn.covariance.EmpiricalCovariance for further details. 

gaussian_score is  the $M_{l}(x_{i})$ feature. You can treat the Mahalanobis feature as the log of a density in multivariate Gaussian with a constant factor. It is fine if you drop -0.5 in training the one-class SVM. 

Hope this helps.

**Comment by RachelTeamo** [comment]
OK, I got it. Thanks very much. But I still have two questions. 
First in line 361 of the code **ood_main.py** you use X_score and -X_scores to calculate results and neg_resuls I wonder why do this operation.  
`  results = detection_performance(X_scores, Y_test, 'mah_logs', tag='TMP')`
  ` neg_resuls = detection_performance(-X_scores, Y_test, 'feats_logs', tag='TMP')`
  ` if sum(results["TMP"].values()) < sum(neg_resuls["TMP"].values()):`
           `results = neg_resuls`
[https://github.com/rivercold/BERT-unsupervised-OOD/blob/main/ood_main.py#L361](url)

another question is in line 89 of calculate_log.py when calculating DTACC why use the .max()  when I check the definition of DTACC in the paper in ICLR, I can't understand this max() operation.
[https://github.com/rivercold/BERT-unsupervised-OOD/blob/main/calculate_log.py#L89](url)

Thanks again.

**Comment by lewisKit** [comment]
Hi, 

- Regarding Scores 
The scores provided by the oc-svm do not indicate that the outlier examples have smaller scores (assumptions made by the methods that use prediction probability as anomaly scores), so we try both side to see which one is better. I think most cases they share the same side. 


- Calculating DTACC
We use the calculate_log from the following repo:
https://github.com/pokaxpoka/deep_Mahalanobis_detector/blob/master/calculate_log.py#L88

**Comment by RachelTeamo** [comment]
OK, I know. Thanks a lot! I have learned a lot from your work!
