### ISSUE TITLE
How can I generate the pretrained model file "bert_clinic_ft_IMLM_BCAD" by myself?

### ISSUE THREAD

**Issue by zhougr18** [rivercold/BERT-unsupervised-OOD#9]
Hello, I'm interested in your work and try to compare with other OOD methods. I find that there are two independent parts of IMLM and BCAD but the best performance can be achieved with both strategies. So I'm wondering how to arrange IMLM and BCAD strategies at the same time. Besides, in the code of IMLM and BCAD parts, the pretrained models are LanguageModelingModel and ClassificationModel while BertForSequenceClassification is used for OOD task, so how can I solve the problem of model parameter mismatch?

**Comment by rivercold** [comment]
Hi, thank you for your question! 

You need to run IMLM and BCAD in sequential order. Check the `Fine-tuning BERT with BCAD and IMLM ` section in README, and you can find for BCAD:`The load_path can be the output of IMLM fine-tuning. If no load_path is specified, then pre-trained bert model is used.`

Regarding the type mismatch, I think shared parameters will be loaded from the checkpoint. The unseen parameter in the new model will be randomly initialized, and exclusive parameters in the checkpoint will be discarded (e.g., LM head after IMLM). No exception will be raised. 

Let me know if you have any further questions.
